/**
 * @file
 * Hooks implementation of test.
 */

/**
 * Returns path to svg sprite.
 */
function _test_get_svg_sprite_path() {
  return base_path() . \Drupal::theme()->getActiveTheme()->getPath() . '/dist/svg/sprite.svg';
}

/**
 * Hook_page_attachments().
 *
 * Prepares test_svg_sprite_path variable to get
 * full path to svg sprite from js.
 */
function test_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['drupalSettings']['test_svg_sprite_path'] = _test_get_svg_sprite_path();
}

/**
 * Hook_preprocess().
 *
 * Prepares test_svg_sprite_path variable to get
 * full path to svg sprite from twig.
 */
function test_preprocess(&$variables, $hook) {
  $variables['test_svg_sprite_path'] = _test_get_svg_sprite_path();
}
